[package]
authors.workspace    = true
description          = "Standard library for Mantrachain with CosmWasm support included"
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "mantrachain-std"
repository.workspace = true
version              = "0.1.0"

[dependencies]
chrono.workspace             = true
cosmwasm-std.workspace       = true
osmosis-std.workspace        = true
osmosis-std-derive.workspace = true
prost.workspace              = true
prost-types.workspace        = true
schemars.workspace           = true

# for query
serde.workspace          = true
serde-cw-value.workspace = true
