[package]
authors.workspace    = true
description          = "Common types for the claimdrop contract."
edition.workspace    = true
homepage.workspace   = true
keywords             = ["mantrachain", "mantra", "claimdrop", "airdrop", "cosmwasm"]
license.workspace    = true
name                 = "mantra-claimdrop-std"
repository.workspace = true
version              = "1.2.1"

[dependencies]
anyhow.workspace                  = true
cosmwasm-schema.workspace         = true
cosmwasm-std.workspace            = true
cw-migrate-error-derive.workspace = true
cw-ownable.workspace              = true
cw-utils.workspace                = true
semver.workspace                  = true
thiserror.workspace               = true
