[package]
authors.workspace = true
edition.workspace = true
name              = "proto-build"
publish           = false
version           = "0.1.0"

[dependencies]
heck.workspace              = true
itertools.workspace         = true
log.workspace               = true
pretty_env_logger.workspace = true
prettyplease.workspace      = true
proc-macro2.workspace       = true
protobuf.workspace          = true
quote.workspace             = true
regex.workspace             = true
serde-protobuf.workspace    = true
syn                         = { workspace = true, features = ["full", "parsing", "extra-traits"] }
walkdir.workspace           = true
